version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    environment:
      - PROFILE=development
    build: .
    volumes:
      - ../src/main/control_panel:/opt/app
      - ../resources:/opt/app/resources
    command: python manage.py runserver 0.0.0.0:3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ../resources/public-variables.env
      - ../resources/env-development.yml
  kafka-consumer:
    environment:
      - PROFILE=development
    build: .
    volumes:
      - ../src/main/control_panel:/opt/app
      - ../resources:/opt/app/resources
      - ../src/test:/opt/app/test
    command: python kafka/entrypoint.py
    links:
      - db
      - zookeeper
      - kafka
    depends_on:
      - db
      - zookeeper
      - kafka
    env_file:
      - ../resources/public-variables.env
      - ../resources/env-development.yml #${env}
  kafka-producer:
      environment:
        - PROFILE=development
      build: .
      volumes:
        - ../src/main/control_panel:/opt/app
        - ../resources:/opt/app/resources
        - ../src/test:/opt/app/test
      command: python kafka/entrypoint.py
      links:
        - db
        - zookeeper
        - kafka
      depends_on:
        - db
        - zookeeper
        - kafka
      env_file:
        - ../resources/public-variables.env
        - ../resources/env-development.yml
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "opportunity.current_plan:1:1,opportunity.current_plan_evaluated:1:1"
