# Generated by Django 2.2 on 2019-08-28 22:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(primary_key=True, serialize=False)),
                ('opportunity_id', models.UUIDField()),
                ('input_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('output_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bind_plan_analysis_opportunity',
            },
        ),
    ]
